Repository questdb/go-questdb-client, pull requests merged in 2024-06, with the labels that each got.

#35 feat(client): add LineSenderFromEnv method
  README.md
  http_sender_test.go
  sender.go
  tcp_sender_test.go
Labels: documentation

#38 fix(client): HTTP sender retries send empty request body
  buffer.go
  http_sender.go
  http_sender_test.go
  integration_test.go
  tcp_sender.go
  utils_test.go
Labels: bug

#36 chore(docs): meaningful example
  .gitignore
  examples/from-conf/main.go
  examples/http/auth-and-tls/main.go
  examples/http/auth/main.go
  examples/http/basic/main.go
Labels: documentation

#39 fix(client): broken HTTP sender retries
  http_sender.go
  http_sender_test.go
  sender.go
  utils_test.go
Labels: bug

#37 feat(client): add support for "off" value in auto_flush_rows and auto_flush_interval
  conf_parse.go
  conf_test.go
  http_sender_test.go
  sender.go
Labels: enhancement

#40 fix(client): fix auto_flush_interval units in LineSenderFromConf
  conf_parse.go
  conf_test.go
  http_sender_test.go
  sender.go
Labels: bug
